# Generated by Django 3.2.4 on 2023-03-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bpjs_cut', models.DecimalField(decimal_places=2, default=0.04, max_digits=2)),
                ('take_home_pay', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christian', 'Christian'), ('Catholic', 'Catholic'), ('Kong Hu Cu', 'Kong Hu Cu'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Other', 'Other')], default='Islam', max_length=10)),
                ('marital', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Widower', 'Widower'), ('Divorced', 'Divorced'), ('Other', 'Other')], default='Single', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_employee', to='employee.position')),
            ],
        ),
    ]
